services:
  postgres:
    image: postgres:15
    container_name: etl_postgres
    restart: always
    env_file: /.env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitcoin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # etl:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.etl
  #   container_name: etl_pipeline
  #   depends_on:
  #     - postgres
  #   env_file: .env
  #   command: ["python", "main.py"]

  # streamlit:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.app
  #   container_name: etl_dashboard
  #   depends_on:
  #     - postgres
  #   env_file: .env
  #   ports:
  #     - "8501:8501"
  #   command: ["streamlit", "run", "app/dashboard.py"]

volumes:
  postgres_data:
